language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini

before_script:
    - travis_retry composer install --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
