language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

script:
    - vendor/bin/tester tests -s

before_script:
    - travis_retry composer install --no-progress --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
